"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.keywords = exports.JWTSECRET = void 0;
exports.JWTSECRET = 'jsonwebtoken-secret-key-is-created-by-using-payload-secret-key-and-a-signature';
exports.keywords = [
    "TikTokTrend",
    "Challenge",
    "DanceChallenge",
    "LifeHacks",
    "Cooking",
    "BeautyTips",
    "Fashion",
    "Travel",
    "Pets",
    "Comedy",
    "Music",
    "Gaming",
    "TikTokPets",
    "LifeLessons",
    "Military",
    'jasonderulo',
    "Fitness",
    "Art",
    "Education",
    "StoryTime",
    "Transition",
    "Foodie",
    "Nature",
    "Viral",
    "Dance",
    "Goals",
    "Couple",
    "Skit",
    "Comedy",
    "Food",
    "Beast",
    "Music",
    "React",
    "Coding",
    "Frontend",
    "khaby",
    "space",
    "Computer",
    "Cars",
    "Super",
    "Amazing",
    "Exotic",
    "love",
    "sensation",
    "music",
    "Song",
    "Agt",
    "America"
];
